services:
  obsy-puppeteer:
    build: .
    container_name: obsy-puppeteer
    ports:
      - "8101:8101"
    restart: unless-stopped
    mem_limit: 1g
    cpus: 0.5

    networks:
      - observer-network

networks:
  observer-network:
    external: true